- hosts: all
  connection: local
  gather_facts: false

  vars:
    panos_beta_version: '9.2.0-b46'
    panos_image_path: /tmp/PanOS_vm-9.2.0-b46
    auth_code: 'your valid VM Auth-Code if unlicensed'

    provider:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Ensure deps are avabilable
      pip:
        name:
          - pan-python
          - pandevice
          - xmltodict
          - requests
          - requests_toolbelt

    - name: Show System Info
      panos_op:
        provider: '{{ provider }}'
        cmd: 'show system info'
      register: system_info
      until: system_info is not failed
      retries: 30
      delay: 60

    - set_fact: system_info_json="{{ system_info.stdout | from_json }}"

    - name: Show Version
      debug: msg="Current Version is {{ system_info_json.response.result.system['sw-version'] }} "

    - name: Activate my authcode
      panos_lic:
        provider: '{{ provider }}'
        auth_code: '{{ auth_code }}'
      register: result

    - debug:
        msg: 'Serial number is {{ result.serialnumber }}'

    - name: Wait for Reboot if necessary
      panos_op:
        provider: '{{ provider }}'
        cmd: 'show system info'
      register: system_info
      until: system_info is not failed
      retries: 30
      delay: 60

    - set_fact: system_info_json="{{ system_info.stdout | from_json }}"

    - name: Check latest content
      panos_op:
        provider: '{{ provider }}'
        cmd: 'request content upgrade check'
      register: check
      changed_when: false

    - name: Download latest content
      panos_op:
        provider: '{{ provider }}'
        cmd: |
          <request><content><upgrade><download>
          <latest></latest>
          </download></upgrade></content></request>
        cmd_is_xml: true
      register: download

    - name: Check content download result
      panos_op:
        provider: '{{ provider }}'
        cmd: 'show jobs id {{ (download.stdout | from_json).response.result.job }}'
      register: download_job
      until: download_job is not failed and (download_job.stdout | from_json).response.result.job.status == 'FIN'
      retries: 10
      delay: 60

    - name: Install latest content
      panos_op:
        provider: '{{ provider }}'
        cmd: |
          <request><content><upgrade><install>
          <version>latest</version>
          </install></upgrade></content></request>
        cmd_is_xml: true
      register: install

    - name: Check content install result
      panos_op:
        provider: '{{ provider }}'
        cmd: 'show jobs id {{ (install.stdout | from_json).response.result.job }}'
      register: install_job
      until: install_job is not failed and (install_job.stdout | from_json).response.result.job.status == 'FIN'
      retries: 10
      delay: 60

    - name: Download PAN-OS 9.0.0 base image only
      panos_software:
        provider: '{{ provider }}'
        version: '9.0.0'
        install: false
        restart: false
      when: |
        system_info_json.response.result.system['sw-version'] is version('9.0.0', '<')

    - name: Install PAN-OS 9.0.8
      panos_software:
        provider: '{{ provider }}'
        version: '9.0.8'
        install: true
        restart: false
      when: |
        system_info_json.response.result.system['sw-version'] is version('9.0.8', '<')

    - name: Download PAN-OS 9.1.0 base image only
      panos_software:
        provider: '{{ provider }}'
        version: '9.1.0'
        install: false
        restart: false
      when: |
        system_info_json.response.result.system['sw-version'] is version('9.1.0', '<')

    - name: Install PAN-OS 9.1.2-h1
      panos_software:
        provider: '{{ provider }}'
        version: '9.1.2-h1'
        install: true
        restart: true
      when: |
        system_info_json.response.result.system['sw-version'] is version('9.1.2-h2', '<')

    - name: Wait for Reboot if necessary
      panos_op:
        provider: '{{ provider }}'
        cmd: 'show system info'
      register: system_info
      until: system_info is not failed
      retries: 30
      delay: 60

    - set_fact: system_info_json="{{ system_info.stdout | from_json }}"

    - name: import beta software upgrade image into PAN-OS
      panos_import:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        file: '{{ panos_image_path }}'
        category: software

    - name: Install target PAN-OS version
      panos_software:
        provider: '{{ provider }}'
        version: '{{ panos_beta_version }}'
        download: false
        install: true
        restart: true

    - name: Pause for restart
      pause:
        seconds: 30

    - name: Check to see if device is ready
      panos_op:
        provider: '{{ provider }}'
        cmd: 'show chassis-ready'
      changed_when: false
      register: result
      until: result is not failed and (result.stdout | from_json).response.result == 'yes'
      retries: 30
      delay: 60

    - name: Update System Information
      panos_op:
        provider: '{{ provider }}'
        cmd: 'show system info'
      register: system_info
      until: system_info is not failed
      retries: 30
      delay: 60

    - name: Display new software rev
      debug: msg="Softare is now {{ system_info_json.response.result.system['sw-version'] }}"